version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:920219963974:task-definition/pms-process:1"
        LoadBalancerInfo:
          ContainerName: "pension-process"
          ContainerPort: "8060"
        PlatformVersion: "LATEST"