version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 920219963974.dkr.ecr.us-east-1.amazonaws.com
    - IMAGE_NAME=pension-portal
    - IMAGE_URI=920219963974.dkr.ecr.us-east-1.amazonaws.com/pension-portal:latest
    - CONTAINER_NAME=pension-portal
    
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
    - cd pensionPortal
    - mvn clean package -Ddockerfile.skip
    - docker build -t $IMAGE_URI . 
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - pensionPortal/imagedefinitions.json